version: '3.8'

services:
  api:
    build:
      context: ./my_memo_master_api
      dockerfile: Dockerfile
      args:
        - API_PORT=${API_PORT}
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./my_memo_master_api:/app
      - api-data:/app/data
    environment:
      - NODE_ENV=development
      - API_PORT=${API_PORT}
    command: sh -c "npm install && npm rebuild sqlite3 && npm start"

  front:
    build:
      context: ./my_memo_master_front
      dockerfile: Dockerfile
      args:
        - VITE_PORT=${VITE_PORT}
    ports:
      - "${VITE_PORT}:${VITE_PORT}"
    volumes:
      - ./my_memo_master_front:/app
      - front-data:/app/data

volumes:
  api-data:
  front-data: