
services:
  postgres:
    build:
      context: ./localPostgres
      dockerfile: Dockerfile-postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${PG_PORT}:${PG_PORT}"

  api:
    build:
      context: ./my_memo_master_api
      dockerfile: Dockerfile
      args:
        - API_PORT=${API_PORT}
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./my_memo_master_api:/app
      - api-data:/app/data
    environment:
      - NODE_ENV=development
      - API_PORT=${API_PORT}
      - PG_USER=${PG_USER}
      - PG_PASS=${PG_PASS}
      - PG_DB=${PG_DB}
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
    command: sh -c "npm install && npm start && npm run seed "

  front:
    build:
      context: ./my_memo_master_front
      dockerfile: Dockerfile
      args:
        - VITE_PORT=${VITE_PORT}
    ports:
      - "${VITE_PORT}:${VITE_PORT}"
    volumes:
      - ./my_memo_master_front:/app
      - front-data:/app/data

  pgadmin:
    build:
      context: ./localPostgres
      dockerfile: Dockerfile-pgadmin
    ports:
      - "${PG_ADMIN_PORT}:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  api-data:
  front-data:
  postgres-data:
  pgadmin-data: