apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mmm.configName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mmm.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
