{{- if .Values.pgadmin.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-pgadmin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mmm.labels" . | nindent 4 }}
    app: {{ .Release.Name }}-pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-pgadmin
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:8
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "mmm.configName" . }}
                  key: PGADMIN_DEFAULT_EMAIL
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mmm.secretName" . }}
                  key: PGADMIN_DEFAULT_PASSWORD
          resources:
            {{- toYaml .Values.pgadmin.resources | nindent 12 }}
{{- end }}
