# ── PostgreSQL ─────────────────────────────────────────────────────────────────
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mmm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-postgres
  ports:
    - port: 5432
      targetPort: 5432

---

# ── Redis ──────────────────────────────────────────────────────────────────────
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mmm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-redis
  ports:
    - port: 6379
      targetPort: 6379

---

# ── API Node.js ────────────────────────────────────────────────────────────────
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mmm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-api
  ports:
    - port: 80
      targetPort: 3000

---

# ── Frontend ───────────────────────────────────────────────────────────────────
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-front
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mmm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-front
  ports:
    - port: 80
      targetPort: 80

{{- if .Values.pgadmin.enabled }}
---

# ── PgAdmin ────────────────────────────────────────────────────────────────────
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pgadmin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mmm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-pgadmin
  ports:
    - port: 80
      targetPort: 80
{{- end }}
