export const routedViews = [
  {
    title: 'Accueil',
    name: 'home',
    path: '/',
    source: 'src/pages/HomePage.vue',
    access: 'Publique',
    summary: "Point d'entree avec menu principal et interpreteur mathematique.",
    dependencies: 'Router local, composants Button/Grid, interpreteur',
    story: 'Home',
    storybookStatus: 'Apercu interactif',
  },
  {
    title: 'Exercises',
    name: 'exercises',
    path: '/exercises',
    source: 'src/pages/ExercisesPage.vue',
    access: 'Privee',
    summary: 'Catalogue des tests avec filtre par matiere et acces a la creation.',
    dependencies: 'Auth guard, store tests, store subjects',
    story: 'Exercises',
    storybookStatus: 'Apercu interactif avec stores simules',
  },
  {
    title: 'Onboarding',
    name: 'onboarding',
    path: '/onboarding',
    source: 'src/pages/OnboardingPage.vue',
    access: 'Privee',
    summary: 'Ecran de mise en route actuellement reduit a un placeholder.',
    dependencies: 'Auth guard',
    story: 'Onboarding',
    storybookStatus: 'Apercu interactif',
  },
  {
    title: 'Tutorials',
    name: 'tutorials',
    path: '/tutorials',
    source: 'src/pages/TutorialsPage.vue',
    access: 'Publique',
    summary: 'Liste de tutoriels avec filtre de sujet et bascule des tips.',
    dependencies: 'Store subjects, donnees locales de tutoriels',
    story: 'Tutorials',
    storybookStatus: 'Apercu interactif avec store subjects simule',
  },
  {
    title: 'Credits',
    name: 'credits',
    path: '/credits',
    source: 'src/pages/CreditsPage.vue',
    access: 'Publique',
    summary: "Tableau de credits et message d'introduction.",
    dependencies: 'Aucune dependance metier',
    story: 'Credits',
    storybookStatus: 'Apercu interactif',
  },
  {
    title: 'Flashcards',
    name: 'flashcards',
    path: '/flashcards',
    source: 'src/pages/FlashcardsPage.vue',
    access: 'Privee',
    summary: 'Vue type Leitner avec saisie question/reponse et recapitulatif.',
    dependencies: 'Auth guard, composants UI locaux',
    story: 'Flashcards',
    storybookStatus: 'Apercu interactif',
  },
  {
    title: 'Mindmaps',
    name: 'mindmaps',
    path: '/mindmaps',
    source: 'src/pages/MindmapsPage.vue',
    access: 'Privee',
    summary: 'Builder de cartes mentales avec liste, autosave, export et edition.',
    dependencies: 'Auth guard, API diagrammes, builder mindmap, toast',
    story: null,
    storybookStatus: 'Documentation seule',
    note: "Vue volontairement non previsualisee car elle depend fortement de l'API et du builder.",
  },
  {
    title: 'Profile',
    name: 'profile',
    path: '/profile',
    source: 'src/pages/ProfilePage.vue',
    access: 'Privee',
    summary: 'Informations utilisateur et action de deconnexion.',
    dependencies: 'Auth guard, store roles, store auth',
    story: 'Profile',
    storybookStatus: 'Apercu interactif avec role simule',
  },
  {
    title: 'Settings',
    name: 'settings',
    path: '/settings',
    source: 'src/pages/SettingsPage.vue',
    access: 'Privee',
    summary: "Panneau de parametres utilisateur et application avec toggles d'apparence.",
    dependencies: 'Auth guard, store roles',
    story: 'Settings',
    storybookStatus: 'Apercu interactif avec role simule',
  },
  {
    title: 'Create Test',
    name: 'create.test',
    path: '/create-test',
    source: 'src/pages/CreateTestPage.vue',
    access: 'Privee',
    summary: 'Construction de quiz avec ajout de questions et zone de preview.',
    dependencies: 'Auth guard, stores tests/questions/responses au clic',
    story: 'CreateTest',
    storybookStatus: 'Apercu interactif',
  },
  {
    title: 'Classroom',
    name: 'classroom',
    path: '/classroom',
    source: 'src/pages/ClassroomPage.vue',
    access: 'Privee',
    summary: 'Placeholder de salle de classe.',
    dependencies: 'Auth guard',
    story: 'Classroom',
    storybookStatus: 'Apercu interactif',
  },
  {
    title: 'Connexion',
    name: 'auth',
    path: '/auth',
    source: 'src/pages/login/ConnexionPage.vue',
    access: 'Publique',
    summary: 'Ecran de connexion avec visuel lateral et formulaire.',
    dependencies: 'Store auth au submit',
    story: 'Login',
    storybookStatus: 'Apercu interactif',
  },
  {
    title: 'Inscription',
    name: 'register',
    path: '/register',
    source: 'src/pages/register/InscriptionPage.vue',
    access: 'Publique',
    summary: "Formulaire d'inscription avec validations cote client.",
    dependencies: 'Store auth au submit',
    story: 'Register',
    storybookStatus: 'Apercu interactif',
    note: 'Le layout applique dans App.vue est celui actuellement utilise par la route.',
  },
  {
    title: 'Mon compte',
    name: 'account',
    path: '/account',
    source: 'src/pages/AccountPage.vue',
    access: 'Privee',
    summary: 'Vue WIP actuellement reduite a un placeholder.',
    dependencies: 'Auth guard',
    story: 'Account',
    storybookStatus: 'Apercu interactif',
  },
  {
    title: 'Erreur 500',
    name: 'error.server',
    path: '/error-server',
    source: 'src/pages/error/ErrorServerPage.vue',
    access: 'Publique',
    summary: 'Page de repli en cas de probleme serveur.',
    dependencies: 'Aucune dependance metier',
    story: 'Error500',
    storybookStatus: 'Apercu interactif',
  },
  {
    title: 'Erreur 404',
    name: 'error.routing',
    path: '/:catchAll(.*)*',
    source: 'src/pages/error/ErrorRoutingPage.vue',
    access: 'Publique',
    summary: 'Page de repli pour les routes inconnues.',
    dependencies: 'Catch-all du routeur',
    story: 'Error404',
    storybookStatus: 'Apercu interactif',
  },
]

export const orphanViews = [
  {
    title: 'AuthPage legacy',
    source: 'src/pages/AuthPage.vue',
    status: 'Non routee',
    summary: 'Placeholder non relie au routeur actuel.',
  },
  {
    title: 'CommunityPage',
    source: 'src/pages/CommunityPage.vue',
    status: 'Non routee',
    summary: 'Placeholder non relie au routeur actuel.',
  },
]
