# File docker-compose.yml
version: "3"

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - my_memo_master_network

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${PG_PORT}:5432"
    networks:
      - my_memo_master_network

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "${PGADMIN_PORT}:${INTERNAL_PG_PORT}"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.mymemomaster.com`)"
      - "traefik.http.routers.pgadmin.entrypoints=web"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=${INTERNAL_PG_PORT}"
    networks:
      - my_memo_master_network

  api:
    image: fredissimo/mymemomaster_api:latest
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - api-data:/app/data
    environment:
      - NODE_ENV=production
      - API_PORT=${API_PORT}
      - PG_USER=${PG_USER}
      - PG_PASS=${PG_PASS}
      - PG_DB=${PG_DB}
      - PG_HOST=${PG_HOST}
      - PG_PORT=5432
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.mymemomaster.com`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.services.api.loadbalancer.server.port=${API_PORT}"
    networks:
      - my_memo_master_network

  front:
    image: fredissimo/mymemomaster_front:latest
    volumes:
      - front-data:/app/data
    ports:
      - "${VITE_PORT}:80"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host(`mymemomaster.com`)"
      - "traefik.http.routers.front.entrypoints=web"
      - "traefik.http.services.front.loadbalancer.server.port=80"
    networks:
      - my_memo_master_network

volumes:
  api-data:
  front-data:
  postgres-data:
  pgadmin-data:

networks:
  my_memo_master_network:
    driver: bridge
