# File docker-compose.yml
version: "3.3"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my_memo_master_preprod_network

  pgadmin:
    image: dpage/pgadmin4:latest
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
    labels:
      - traefik.enable=true
      - traefik.http.routers.mmm-preprod-pgadmin.rule=Host(`pgadmin.tests.my-memo-master.com`)
      - traefik.http.routers.mmm-preprod-pgadmin.entrypoints=websecure
      - traefik.http.routers.mmm-preprod-pgadmin.tls.certresolver=letsencrypt
      - traefik.http.services.mmm-preprod-pgadmin.loadbalancer.server.port=80
    networks:
      - my_memo_master_preprod_network
      - traefik_proxy

  api:
    image: fredissimo/mymemomaster_test_api:latest
    env_file:
      - .env
    volumes:
      - api-data:/app/data
    environment:
      - NODE_ENV=production
      - API_PORT=${API_PORT}
      - PG_USER=${PG_USER}
      - PG_PASS=${PG_PASS}
      - PG_DB=${PG_DB}
      - PG_HOST=${PG_HOST}
      - PG_PORT=5432
    depends_on:
      - postgres
    labels:
      - traefik.enable=true
      - traefik.http.routers.mmm-preprod-api.rule=Host(`api.tests.my-memo-master.com`)
      - traefik.http.routers.mmm-preprod-api.entrypoints=websecure
      - traefik.http.routers.mmm-preprod-api.tls.certresolver=letsencrypt
      - traefik.http.services.mmm-preprod-api.loadbalancer.server.port=${API_PORT}
    networks:
      - my_memo_master_preprod_network
      - traefik_proxy
    restart: unless-stopped

  front:
    image: fredissimo/mymemomaster_test_front:latest
    volumes:
      - front-data:/app/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.mmm-preprod-front.rule=Host(`tests.my-memo-master.com`)
      - traefik.http.routers.mmm-preprod-front.entrypoints=websecure
      - traefik.http.routers.mmm-preprod-front.tls.certresolver=letsencrypt
    networks:
      - my_memo_master_preprod_network
      - traefik_proxy
    restart: unless-stopped

volumes:
  api-data:
  front-data:
  postgres-data:
  pgadmin-data:

networks:
  my_memo_master_preprod_network:
    driver: bridge
  traefik_proxy:
    external: true

