apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sq.configName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sq.labels" . | nindent 4 }}
data:
  PG_DB: {{ .Values.config.PG_DB | quote }}
