on:
  push:
    branches:
      - 'dev_back_*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: API - Install dependencies
        working-directory: my_memo_master_api
        run: npm install
      - name: API - Test
        working-directory: my_memo_master_api
        run: npm run test
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: API - Install dependencies
        working-directory: my_memo_master_api
        run: npm install
      - name: API - Lint
        run: npm run lint
  notify_failure:
    runs-on: ubuntu-latest
    needs: [test, lint]
    if: failure()
    steps:
      - name: Send message to Discord
        run: |
          URLS=(
            "https://media1.tenor.com/m/4CtiBiTdmioAAAAC/vilebrequin-sylvain.gif"
            "https://media1.tenor.com/m/GgnOYuwPdAIAAAAC/vilebrequin-sylvain.gif"
            "https://media1.tenor.com/m/OlLPEZbtPEYAAAAd/vilebrequin-vilebrequin-telemerding.gif"
            "https://media1.tenor.com/m/-o0dTiU5Ow4AAAAd/vilebrequin-vilebrequin-cpt.gif"
            "https://media1.tenor.com/m/eMOeGcx_o54AAAAd/crash-bus.gif"
            "https://media1.tenor.com/m/0y5lOt_Y450AAAAd/vilebrequin-vilebrequin-cpt.gif"
            "https://media1.tenor.com/m/hoRt31ZDmPEAAAAC/vilebrequin-sylvain.gif"
            "https://media1.tenor.com/m/gD2lZPrYVW4AAAAC/vilebrequin-vilebrequin-sylvain-levy.gif"
            "https://media1.tenor.com/m/sBEng5B5vbwAAAAC/cat-cats.gif"
            "https://media1.tenor.com/m/1c70Jy7WZI8AAAAd/cat.gif"
          )
          RANDOM_URL=${URLS[$RANDOM % ${#URLS[@]}]}
          BRANCH_NAME=${GITHUB_REF##*/}
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"content\": \"Tests failed on branch $BRANCH_NAME! $RANDOM_URL\"}" \
          ${{ secrets.DISCORD_LOG }}

  notify_success:
    runs-on: ubuntu-latest
    needs: [test, lint]
    if: success()
    steps:
      - name: Send success message to Discord
        run: |
          URLS=(
            "https://media1.tenor.com/m/BhPivX5RaGgAAAAd/vilebrequin-vilbrequin.gif"
            "https://media1.tenor.com/m/-c-taOTKNN8AAAAd/vilebrequin-sylvain.gif"
            "https://media1.tenor.com/m/4Nxe3sCkjVcAAAAd/vilebrequin-vilbrequin.gif"
            "https://media1.tenor.com/m/uPogt0rnqKoAAAAd/rosycheeks-approved.gif"
            "https://media1.tenor.com/m/eAwDugg8aBgAAAAd/kitty-meow.gif"
            "https://media1.tenor.com/m/wjS2sXen8iMAAAAd/stonks-up-stongs.gif"
          )
          RANDOM_URL=${URLS[$RANDOM % ${#URLS[@]}]}
          BRANCH_NAME=${GITHUB_REF##*/}
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"content\": \"Tests succeeded on branch $BRANCH_NAME! $RANDOM_URL\"}" \
          ${{ secrets.DISCORD_LOG }}
